# Generated by Django 5.2.4 on 2025-08-19 04:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('food_status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('not_applicable', 'Not Applicable')], default='pending', max_length=50)),
                ('beverage_status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waiter_notified_beverage', models.CharField(blank=True, choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('not_applicable', 'Not Applicable')], default='pending', max_length=50, null=True)),
                ('cashier_status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed')], default='pending', max_length=20)),
                ('payment_option', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True)),
                ('receipt_image', models.ImageField(blank=True, help_text='Payment receipt image for online payments', null=True, upload_to='receipts/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('beverage', 'beverage'), ('meat', 'Meat')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('addition', 'Item Addition'), ('modification', 'Item Modification'), ('removal', 'Item Removal'), ('quantity_change', 'Quantity Change'), ('status_change', 'Status Change')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('items_changes', models.JSONField(default=dict, help_text='JSON containing the items being added/modified/removed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this update')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('total_addition_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Update',
                'verbose_name_plural': 'Order Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
