# Generated by Django 5.2.3 on 2025-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('processed', 'Processed')], default='pending', max_length=20),
        ),
    ]
