# Generated by Django 5.2.4 on 2025-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='beverage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
    ]
