# Generated by Django 5.2.4 on 2025-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_cashier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed')], default='pending', max_length=20),
        ),
    ]
