# Generated by Django 5.2.4 on 2025-08-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='beverage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('not_applicable', 'Not Applicable')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter_notified_beverage',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('not_applicable', 'Not Applicable')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
