# Generated by Django 5.2.4 on 2025-08-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_cashier_status'),
        ('orders', '0003_alter_order_beverage_status_alter_order_food_status_and_more'),
    ]

    operations = [
    ]
