# Generated by Django 5.2.4 on 2025-08-14 09:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20250814_0954'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('addition', 'Item Addition'), ('modification', 'Item Modification'), ('removal', 'Item Removal'), ('quantity_change', 'Quantity Change'), ('status_change', 'Status Change')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('items_changes', models.JSONField(default=dict, help_text='JSON containing the items being added/modified/removed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this update')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('total_addition_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updates_created', to=settings.AUTH_USER_MODEL)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updates_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Update',
                'verbose_name_plural': 'Order Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
