# Generated by Django 5.2.3 on 2025-06-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_status_order_drink_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
