# Generated by Django 5.2.4 on 2025-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_cashier_status_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Payment receipt image for online payments', null=True, upload_to='receipts/'),
        ),
    ]
