# Generated by Django 5.2.3 on 2025-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_total_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter_notified_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_notified_food',
            field=models.BooleanField(default=False),
        ),
    ]
