# Generated by Django 5.2.3 on 2025-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_waiter_notified_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiter_notified_food',
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter_notified_drink',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('not_applicable', 'Not Applicable')], default='pending', max_length=50, null=True),
        ),
    ]
