# Generated by Django 5.2.3 on 2025-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_waiter_notified_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed')], default='pending', max_length=20),
        ),
    ]
