# Generated by Django 5.2.3 on 2025-06-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAudit',
        ),
    ]
