# Generated by Django 5.2.3 on 2025-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_delete_orderaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True),
        ),
    ]
