# Generated by Django 5.2.3 on 2025-06-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
