# Generated by Django 5.2.3 on 2025-06-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
