# Generated by Django 5.2.3 on 2025-06-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='products.itemtype'),
        ),
    ]
