# Generated by Django 5.2.4 on 2025-08-19 04:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarmanStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_base_units', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_threshold_base_units', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('running_out', models.BooleanField(default=False)),
                ('last_stock_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Barman Stock',
                'verbose_name_plural': 'Barman Stocks',
                'ordering': ['bartender__username', 'stock__product__name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['item_type__type_name', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Quantity requested in the specified 'request_unit'", max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=10)),
                ('reached_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Request',
                'verbose_name_plural': 'Inventory Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('restock', 'Restock (Inbound)'), ('sale', 'Sale (Outbound)'), ('wastage', 'Wastage (Outbound)'), ('store_to_barman', 'Transfer Store to Barman'), ('barman_to_store', 'Transfer Barman to Store'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Quantity in the specified 'transaction_unit'", max_digits=10)),
                ('quantity_in_base_units', models.DecimalField(decimal_places=2, default=0.0, help_text="Calculated quantity in the product's base unit. Positive for increases, negative for decreases.", max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_at_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_per_base_unit_ml', models.DecimalField(blank=True, decimal_places=2, help_text="For liquids: volume of one 'base_unit' in milliliters. E.g., 750 for a bottle of wine.", max_digits=10, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='product_receipts/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this product currently available?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per', models.DecimalField(decimal_places=4, help_text="How many 'to_unit' are in one 'from_unit' (e.g., 24 for bottles per carton, 20 for shots per bottle)", max_digits=10)),
                ('is_default_sales_unit', models.BooleanField(default=False, help_text='Set as True if this is a primary unit for selling this product.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Measurement Conversion',
                'verbose_name_plural': 'Product Measurement Conversions',
                'ordering': ['product__name', 'from_unit__unit_name', 'to_unit__unit_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text="e.g., 'bottle', 'carton', 'liter', 'shot', 'ml', 'piece'", max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('is_liquid_unit', models.BooleanField(default=False, help_text='True if this unit measures liquid volume (e.g., liter, ml, shot, glass)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_base_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Total quantity in the product's base unit (e.g., total bottles, total liters).", max_digits=10)),
                ('minimum_threshold_base_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Minimum stock level in base units before 'running_out' is flagged.", max_digits=10)),
                ('running_out', models.BooleanField(default=False, help_text='True if stock is below the minimum threshold.')),
                ('last_stock_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original quantity in its original unit (e.g. cartons)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Main Store Stock',
                'verbose_name_plural': 'Main Store Stocks',
                'ordering': ['branch__name', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(help_text="Type of action (e.g., 'restock', 'sale', 'create', 'update')", max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='JSON payload with detailed changes or transaction data.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
