# Generated by Django 5.2.4 on 2025-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='reached_status',
            field=models.BooleanField(default=False),
        ),
    ]
