# Generated by Django 5.2.4 on 2025-08-22 16:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='initial_stock_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The initial stock amount when first added (e.g., 10 cartons of Mirinda). This value should not change once set.', max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_stock_unit',
            field=models.ForeignKey(blank=True, help_text='The unit of the initial stock amount (e.g., carton, box, bottle)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_initial_unit', to='inventory.productunit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='original_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current quantity in its original unit (e.g. cartons) - decreases when stock is used', max_digits=10),
        ),
    ]
