# Generated by Django 5.2.4 on 2025-07-21 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text="The fundamental unit for this product's inventory tracking and base price (e.g., 'bottle' for Pepsi, 'liter' for Tej).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base_unit', to='inventory.productunit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
