# Generated by Django 5.2.4 on 2025-07-21 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit Log Entry', 'verbose_name_plural': 'Audit Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Branch Stock', 'verbose_name_plural': 'Branch Stocks'},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='quantity',
            new_name='original_action_quantity',
        ),
        migrations.RenameField(
            model_name='barmanstock',
            old_name='unit_quantity',
            new_name='total_sellable_units',
        ),
        migrations.RenameField(
            model_name='inventoryrequest',
            old_name='quantity',
            new_name='quantity_in_sellable_units',
        ),
        migrations.RenameField(
            model_name='inventorytransaction',
            old_name='purchase_price',
            new_name='purchase_price_per_stocking_unit',
        ),
        migrations.RenameField(
            model_name='inventorytransaction',
            old_name='quantity',
            new_name='quantity_in_sellable_units',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_per_unit',
            new_name='price_per_sellable_unit',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='unit_quantity',
            new_name='total_sellable_units',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='barmanstock',
            name='bottle_quantity',
        ),
        migrations.RemoveField(
            model_name='barmanstock',
            name='carton_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bottles_per_carton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uses_carton',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bottle_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='carton_quantity',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='inventory_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryrequest'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='original_action_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='quantity_affected_sellable_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='fulfilling_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_inventory_requests', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='requested_unit_type',
            field=models.CharField(blank=True, choices=[('carton', 'Carton'), ('bottle', 'Bottle'), ('liter', 'Liter'), ('kilogram', 'Kilogram'), ('piece', 'Piece'), ('piece', 'Piece'), ('shot', 'Shot'), ('glass', 'Glass'), ('unit', 'Unit')], help_text="The unit in which the request was originally made (e.g., 'carton').", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='requesting_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_inventory_requests', to='branches.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='original_quantity_entered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original quantity entered for restocks (e.g., 5 for 5 cartons).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='original_unit_type_entered',
            field=models.CharField(blank=True, help_text="Original unit type entered for restocks (e.g., 'carton').", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Number of sellable units per primary stocking unit.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_stocking_unit',
            field=models.CharField(choices=[('carton', 'Carton'), ('bottle', 'Bottle'), ('liter', 'Liter'), ('kilogram', 'Kilogram'), ('piece', 'Piece')], default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sellable_unit_type',
            field=models.CharField(choices=[('piece', 'Piece'), ('shot', 'Shot'), ('glass', 'Glass'), ('unit', 'Unit')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create_product', 'Product Created'), ('update_product', 'Product Updated'), ('stock_add', 'Stock Added (Branch)'), ('stock_deduct', 'Stock Deducted (Branch)'), ('barman_stock_add', 'Stock Added (Barman)'), ('barman_stock_deduct', 'Stock Deducted (Barman)'), ('restock_transaction', 'Restock Transaction'), ('sale_transaction', 'Sale Transaction'), ('wastage_transaction', 'Wastage Transaction'), ('inventory_request_created', 'Inventory Request Created'), ('inventory_request_status_change', 'Inventory Request Status Change'), ('threshold_alert', 'Threshold Alert Triggered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='barmanstock',
            name='minimum_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('wastage', 'Wastage'), ('transfer_in', 'Transfer In (from another branch/main)'), ('transfer_out', 'Transfer Out (to another branch/barman)')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('item_type', 'category_name')},
        ),
    ]
