# Generated by Django 5.2.3 on 2025-06-26 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_added_by_inventoryitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='requested_by',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece'), ('plate', 'Plate'), ('shot', 'Shot'), ('bottle', 'Bottle'), ('carton', 'Carton')], max_length=20)),
                ('quantity_per_carton', models.IntegerField(blank=True, default=0, null=True)),
                ('volume_per_bottle_ml', models.IntegerField(blank=True, default=0, null=True)),
                ('volume_per_shot_ml', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_in_bottles', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_in_ml', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_in_kg', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('stock_in_pieces', models.IntegerField(blank=True, default=0, null=True)),
                ('running_out', models.BooleanField(default=False)),
                ('minimum_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece'), ('plate', 'Plate'), ('shot', 'Shot'), ('bottle', 'Bottle'), ('carton', 'Carton')], max_length=20)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('wastage', 'Wastage')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece'), ('plate', 'Plate'), ('shot', 'Shot'), ('bottle', 'Bottle'), ('carton', 'Carton')], max_length=20)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryRequest',
        ),
    ]
