# Generated by Django 5.2.4 on 2025-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='running_out',
        ),
        migrations.AddField(
            model_name='stock',
            name='minimum_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='running_out',
            field=models.BooleanField(default=False),
        ),
    ]
