# Generated by Django 5.2.4 on 2025-08-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_initial_stock_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='How many base units are in one input unit (e.g., 24 bottles per carton)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='input_unit',
            field=models.ForeignKey(blank=True, help_text="The unit used when adding stock (e.g., 'carton', 'box')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_input_unit', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_type', to='inventory.itemtype'),
        ),
        migrations.AddField(
            model_name='stock',
            name='calculated_base_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated base units from input_quantity * conversion_amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='input_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The input quantity from the Add Product form (e.g., 10 cartons)', max_digits=10, null=True),
        ),
    ]
