# Generated by Django 5.2.4 on 2025-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bottles_per_carton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uses_carton',
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Amount per product (e.g., units per carton, bottles per pack, etc.)', max_digits=10),
        ),
    ]
