# Generated by Django 5.2.4 on 2025-07-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryrequest_reached_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarmanStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_quantity', models.PositiveIntegerField(default=0)),
                ('bottle_quantity', models.PositiveIntegerField(default=0)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('running_out', models.BooleanField(default=False)),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barman_stocks', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Barman Stock',
                'verbose_name_plural': 'Barman Stocks',
                'unique_together': {('stock', 'bartender')},
            },
        ),
    ]
