# Generated by Django 5.2.3 on 2025-06-26 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemtype_remove_inventoryrequest_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_per_carton',
            new_name='bottle_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_in_bottles',
            new_name='bottles_per_carton',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_in_ml',
            new_name='carton_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_in_kg',
            new_name='unit_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_in_pieces',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_per_bottle_ml',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_per_shot_ml',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='product',
            name='uses_carton',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('wastage', 'Wastage')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('carton', 'Carton'), ('bottle', 'Bottle'), ('unit', 'Unit')], max_length=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
