# Generated by Django 5.2.4 on 2025-08-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_conversion_amount_product_input_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_per_base_unit_ml',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='initial_stock_amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='initial_stock_unit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_stock_update',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='original_unit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_in_base_units',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='running_out',
        ),
    ]
