# Generated by Django 5.2.4 on 2025-07-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_barmanstock_original_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barmanstock',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='original_unit',
        ),
        migrations.AlterField(
            model_name='barmanstock',
            name='original_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The quantity of the product as it was originally received (e.g., '2 bottles' of wine).", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='barmanstock',
            name='original_unit',
            field=models.ForeignKey(blank=True, help_text="The unit in which the product was originally received (e.g., 'bottle').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barmanstock_original_unit', to='inventory.productunit'),
        ),
    ]
