# Generated by Django 5.2.4 on 2025-07-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0004_remove_barmanstock_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmanstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barman_product_stocks', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='original_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='original_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_original_unit', to='inventory.productunit'),
        ),
    ]
