# Generated by Django 5.2.4 on 2025-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmanstock',
            name='minimum_threshold',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
