# Generated by Django 5.2.4 on 2025-07-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='purchase_price',
        ),
    ]
