# Generated by Django 5.2.4 on 2025-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_update_itemtype_category_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['item_type__type_name', 'sort_order', 'category_name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='quantity_in_base_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity in base units (e.g., bottles)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='quantity_in_input_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity in input units (e.g., cartons)', max_digits=10, null=True),
        ),
    ]
