# Generated by Django 5.2.4 on 2025-07-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_barmanstock_original_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barmanstock',
            name='original_quantity',
        ),
    ]
