# Generated by Django 5.2.4 on 2025-07-25 07:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_barmanstock_original_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='original_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original quantity in its original unit (e.g. cartons)', max_digits=10),
        ),
    ]
