# Generated by Django 5.2.3 on 2025-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'branch')},
        ),
    ]
