# Generated by Django 5.2.4 on 2025-08-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('orders', '0006_order_receipt_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'branch')},
        ),
        migrations.AddField(
            model_name='table',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_table', to='orders.order'),
        ),
        migrations.AddField(
            model_name='table',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('ordering', 'Ordering'), ('ready_to_pay', 'Ready to Pay'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
    ]
