# Generated by Django 5.2.3 on 2025-07-11 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_table_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'created_by')},
        ),
    ]
