# Generated by Django 5.2.4 on 2025-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='item_type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('beverage', 'Beverage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('name', 'item_type')},
        ),
    ]
