# Generated by Django 5.2.3 on 2025-07-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_update_barman_stock_fields'),
        ('menu', '0003_fix_category_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.RemoveField(
            model_name='menusection',
            name='menu',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuSection',
        ),
    ]
