# Generated by Django 5.2.3 on 2025-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_created_at_alter_menu_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menu.menuitem'),
        ),
    ]
