# Generated by Django 5.2.3 on 2025-06-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0003_add_phone_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('bartender', 'Bartender'), ('meat', 'Meat Counter'), ('cashier', 'Cashier'), ('manager', 'Branch Manager'), ('owner', 'Owner')], default='waiter', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
