# Generated by Django 5.2.4 on 2025-07-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250718_1716'),
    ]

    operations = [
    ]
